### ISSUE TITLE
Use vector-tile for geometry/property handling

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#25]
@flippmoke has been working on a new version of lib vector-tile over at https://github.com/mapbox/vector-tile/tree/2.x - let's start using some of the helpful methods there!

**Comment by springmeyer** [comment]
👍  for geometry handling. For property handling however, like shaver, I'm less certain that the generic solution that we currently offer in `mapbox/vector-tile` will be appropriate. (and I've mentioned this to @flippmoke). The issue I see is that `mapbox/vector-tile` will use the `property_map` type from `mapbox::geometry::feature` (or `mapbox::feature` if you use https://github.com/mapbox/geometry.hpp/pull/52). And this `property_map` is a `std::map`. And unless you need to search it frequently `std::map` is a less efficient choice because it is more expensive to create than `std::vector<std::pair<key_type,value_type>>` per https://github.com/mapbox/vt-shaver-cpp/commit/aea952ef4a26a24e393c8022dd51599f2b170b68 and `Use more appropriate container types` at #30.

So, my opinion is that performance matters enough in vtzero that we should be using external deps only if they increase performance.

**Comment by mapsam** [comment]
Resolved in #42 and a major increase in perf!
