### ISSUE TITLE
Use comparable_distance spatial-algorithms

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#33]
From @artemp 

> noticed that distance returned from `closest_point` is only used internally in your code.  So simple optimisation is to use `comparable_distance` (in case of pythagoras strategy it's a d*d) for internal calculations. I created branch https://github.com/mapbox/spatial-algorithms/tree/comparable_distance for you to try and see if it helps with performance.

https://github.com/mapbox/spatial-algorithms/tree/comparable_distance

**Comment by springmeyer** [comment]
Took a re-look at this. I opened `mason_packages/headers/spatial-algorithms/0.1.0/include/boost/geometry/extensions/strategies/cartesian/closest_point.hpp` locally and changed:

```c++
namespace strategy { namespace distance
{

template
<
    typename CalculationType = void,
    typename Strategy = pythagoras<CalculationType>
>
```

to:

```c++
namespace strategy { namespace distance
{

template
<
    typename CalculationType = void,
    typename Strategy = comparable::pythagoras<CalculationType>
>
```

And re-ran the benchmarks with `node bench/vtquery.bench.js --iterations 500 --concurrency 1` and did not pick up on any difference. I presume this is because other bottlenecks (like geometry allocation - #55) are so large as to not make the impl of comparable difference matter.

So, I think this can be closed unless my methodology is flawed or I'm missing something.

**Comment by mapsam** [comment]
Thanks for taking a peek @springmeyer. Assuming tests were still passing with your changes, let's assume there isn't a big benefit here. Closing!
