### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#6]
Let's set up a benchmark script based on the [node-cpp-skel async benchmarks](https://github.com/mapbox/node-cpp-skel/blob/master/bench/hello_async.bench.js) so we can work through different looping ideas and sorting styles.

Other than total time, it'd be great to benchmark individual pieces of this process, such as:

* sorting
* vtzero reading
* sending JSON back to node
* more...

cc @springmeyer @GretaCB

**Comment by springmeyer** [comment]
@mapsam - I would be very interested, once the basic implementation is working, for you to benchmark rough performance against node-mapnik's `vtile.query`.

The reason is that the results I think should help guide level of effort and potentially what related pushes we invest in.

For example if the speed is similar, then I'd be concerned that `closest_point` is expensive (we'd of course confirm with profiling) and we'll then want to prioritize investment in trying `contains, within, or covers` instead per https://github.com/mapbox/vtquery/issues/13#issuecomment-336529516 (when radius=0). Or potentially looking at what is slow inside `closest_point` and trying to optimize it.

If the speed is faster, then that would be exciting since we'd then know we have room to do more while keeping the current API latency similar: like querying more surrounding tiles to support larger radius values without needing to jump to parent tiles (that might not contain all the features).

Note: Since node-mapnik only takes one tile, we'd stick to one tile for 🍏  to 🍏.

**Comment by mapsam** [comment]
Benchmarks have been set up and are now helping us make decisions when profiling and making updates!

They can be run like so:

```
node bench/vtquery.bench.js --iterations=1000 --concurrency=1
```
