### ISSUE TITLE
vtzero::convert_property_value inside worker

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#82]
The [`set_property`](https://github.com/mapbox/vtquery/blob/95ab3478f9403b55b89eccf25e6a2bf2777c3353/src/vtquery.cpp#L389) method does some variant decoding in the main thread while constructing the final JSON object to return to node. This, in theory, could happen within the worker threads before being handled in the callback, and increase performance.

https://github.com/mapbox/vtquery/blob/95ab3478f9403b55b89eccf25e6a2bf2777c3353/src/vtquery.cpp#L154-L160

cc @springmeyer @flippmoke

**Comment by springmeyer** [comment]
@mapsam, this change is implemented already in https://github.com/mapbox/vtquery/pull/73: see the `properties_vector_materialized` member of the `ResultObject`. It is REQUIRED in the case of #73 because the actual properties are no longer in scope after returning from the threadpool (because the buffer, in the gzip case, is not alive outside the threadpool). See https://github.com/mapbox/vtquery/pull/73/files#diff-d293222b917c4d9edf75c1288538554fR378 for more details.

**Comment by mapsam** [comment]
Oh awesome @springmeyer - thanks for pointing that out! 0.2.0 was just released, so perhaps we can work on this going out in 0.3.0?

**Comment by springmeyer** [comment]
Done in #95
